
services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.backend.dev
  #   ports:
  #     - "8888:8888"
  #   volumes:
  #     - ./:/usr/src/service
  #   environment:
  #     -
  #     DATABASE_URL=postgres://dev:wE0PvMXHdHgOF6aaKxqFfjkl78943hjk8fHj2YODCxLk@postgres:5432/{{project-name}}
  #     - PORT=8888
  #   depends_on:
  #     - postgres
  #   command: bash -c "cargo watch -x 'run --bin {{project-name}}'"

  # DATABASE_URL=postgres://dev:wE0PvMXHdHgOF6aaKxqFfjkl78943hjk8fHj2YODCxLk@localhost:5432/{{project-name}}
  postgres:
    container_name: {{project-name}}_db
    image: postgres:15.4
    environment:
      POSTGRES_USER: dev 
      POSTGRES_PASSWORD: wE0PvMXHdHgOF6aaKxqFfjkl78943hjk8fHj2YODCxLk
      POSTGRES_DB: {{project-name}}
      PGDATA: /data/postgres
    volumes:
      - {{project-name}}_db:/data/postgres
    ports:
      - "5432:5432"
volumes:
  {{project-name}}_db:
    driver: local
